Fix Spam Plugin onRadio event handling
Fix for error:

"SpamcontrolPlugin: could not parse event Event client radio: onRadio()
missing 1 required positional argument: 'event'"